name: RRPGSocial
version: 0.0.1
authors: [ShawnClake, QuinnBast]
main: com.openrubicon.social.RRPGSocial
depend: [RRPGCore]
database: true
website: https://github.com/OpenRubiconProject
commands:
      rrpg-social:
               description: Spits out the current status of Rubicon Social and its versions
               usage: /rrpg-social
      rrpg friend add <Friend>:
               description: Sends a friend request to the specified player
               usage: /rrpg friend add <FriendModel>
      rrpg friend add best <Friend>:
               description: Sends a best friend request to the specified player
               usage: /rrpg friend add best <FriendModel>
      rrpg friend remove <Friend>:
               description: Removes the specified friend from your friend list
               usage: /rrpg friend remove <FriendModel>
      rrpg item send <Friend>:
               description: Sends an item to the specified player.
               usage: /rrpg friend item send <FriendModel>
      rrpg friend list:
               description: Shows your friend list
               usage: /rrpg friend list
      rrpg friend requests:
                description: Shows your friend requests
                usage: /rrpg friend requests